/** @type {import('knip').KnipConfig} */
export default {
  entry: ["src/index.ts", "src/agent-cli.ts"],
  project: ["src/**/*.ts", "tests/**/*.ts"],
  ignoreDependencies: [
    "@types/node",
    "@types/express",
    "@vitest/coverage-v8",
    "eslint",
    "typescript-eslint",
    "@eslint/js",
    "eslint-plugin-unicorn",
    "eslint-plugin-security",
    "eslint-plugin-import-x",
    "semantic-release",
    "@semantic-release/changelog",
    "@semantic-release/github",
    "@semantic-release/npm",
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/git",
    "@semantic-release/exec",
    "@commitlint/cli",
    "@commitlint/config-conventional",
    "husky",
    "lint-staged",
    "knip",
  ],
  ignore: [
    "knip.config.mjs",
    "eslint.config.mjs",
    "commitlint.config.mjs",
    "vitest.config.ts",
    "vitest.e2e.config.ts",
  ],
  rules: {
    files: "warn",
    dependencies: "error",
    devDependencies: "warn",
    exports: "warn",
    types: "warn",
  },
};
