import type { Logger } from '../alerts/index.js'
import type { Config } from '../config.js'
import { resolveBridgeConfig } from '../config.js'
import { ImapClient } from '../imap.js'
import { SmtpClient } from '../smtp.js'
import type { SetupReport } from './goals.js'

export async function runImapCheck(
  cfg: Config,
  log: Logger,
): Promise<SetupReport> {
  const report: SetupReport = {
    bridgeReachable: false,
    imapOk: false,
    smtpOk: false,
    authOk: false,
    folders: [],
    recommendations: [],
  }

  const bridgeCfg = await resolveBridgeConfig(cfg, log)
  const imap = new ImapClient(bridgeCfg, log)
  try {
    const folders = await imap.listMailboxes()
    report.bridgeReachable = true
    report.imapOk = true
    report.authOk = true
    report.folders = folders.map((f) => f.path)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    log.error('IMAP setup check failed', { error: msg })
    if (msg.includes('ECONNREFUSED')) {
      report.recommendations.push(
        'Proton Mail Bridge no está escuchando IMAP. Verifica que esté corriendo y el puerto.',
      )
    } else if (msg.toLowerCase().includes('auth')) {
      report.recommendations.push(
        'Bridge rechazó las credenciales. Revisa PROTON_BRIDGE_USER y PROTON_BRIDGE_PASS.',
      )
    } else {
      report.recommendations.push(`Fallo IMAP: ${msg}`)
    }
  } finally {
    await imap.close().catch(() => {
      /* noop */
    })
  }

  if (!report.folders.includes('INBOX')) {
    report.recommendations.push(
      'No se detectó INBOX. Revisa la configuración de cuenta en Bridge.',
    )
  }

  return report
}

export async function runSetup(cfg: Config, log: Logger): Promise<SetupReport> {
  const report = await runImapCheck(cfg, log)
  if (!report.imapOk) {
    return report
  }

  const bridgeCfg = await resolveBridgeConfig(cfg, log)
  const smtp = new SmtpClient(bridgeCfg, log)
  try {
    await smtp.send({
      to: [cfg.products.mail.bridge.from],
      subject: 'ProtonMail Agent setup verification',
      text: 'This is a self-addressed verification message generated by the agent setup pipeline.',
    })
    report.smtpOk = true
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    log.error('SMTP setup check failed', { error: msg })
    report.recommendations.push(`SMTP no disponible: ${msg}`)
  } finally {
    smtp.close()
  }

  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (report.imapOk && report.smtpOk) {
    report.recommendations.push(
      "Bridge está configurado correctamente. Puedes ejecutar 'agent:organize' para analizar el buzón.",
    )
  }

  return report
}
