#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
pnpm typecheck
pnpm test
npx markdownlint-cli2 --config .markdownlint-cli2.jsonc "**/*.md"
bash "$(dirname "$0")/../scripts/run-actionlint.sh"
